service: messcat

frameworkVersion: '2'
useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  region: ap-south-1
  apiName: messcat
  lambdaHashingVersion: 20201221

functions:
  wa-hook:
    handler: src/index.hook
    events:
        - http:
            path: /wa-hook
            method: post